---
title: Stichprobenstatistik
---

Die deskriptive Statistik hat zum Ziel, empirische Daten durch Tabellen und
Grafiken übersichtlich darzustellen und zu ordnen, sowie durch geeignete
grundlegende Kenngrößen zahlenmäßig zu beschreiben.

Eine Tabelle oder Grafik informiert über die gesamte Verteilung eines Merkmals mit
seinen Ausprägungen. Demgegenüber sagen statistische Kenngrößen etwas über
spezielle Eigenschaften der Verteilung aus.  

- **Lagekenngrößen:** beschreiben Stellen, an denen sich die Daten konzentrieren oder die die Verteilung in gleiche Teile unterteilen.  
- **Streuungskenngrößen:**  messen die Ausbreitung und Variabilität der Daten.  
- **Formmaße:** messen die Symmetrie und den "Schwanz" der Verteilung.

Diese Werte werden auch genannt **Stichprobenstatistiken** genannt.

Die zahlenmäßige Darstellung durch statistische Kenngrößen beruht auf einer
Reduktion der Daten. Die Gesamtheit des Datenmaterials wird hierbei durch
typische Vertreter repräsentiert.


## Lagekenngrößen

Es werden zwei Gruppen von Lagekenngrößen unterschieden:  

- Zentrale Lagewerte messen die Werte, an denen sich die Daten konzentrieren, meist im Zentrum der Verteilung. Diese Werte sind diejenigen, die die Stichprobe am besten darstellen. Die wichtigsten sind:  
  - Arithmetisches Mittel (Mittelwert)
  - Median  
  - Modal (Modus)
- Nicht-zentrale Lagewerte teilen die Stichprobe in gleichgroße Teile. Die wichtigsten sind:  
  - Quartile.  
  - Dezile.  
  - Perzentile.  


### Arithmetischer Mittelwert  

::: {.callout-warning appearance="default"}
##  Definition "Arithmetisches Mittel $\bar x$"

Das arithmetische Mittel (umgangssprachlich *Mittelwert*) einer Variablen $X$ ist die Summe der beobachteten Werte in der Stichprobe geteilt durch die Stichprobengröße $n$ und wird durch das Symbol $\bar x$ (sprich "x quer") dargestellt.  

$$
\bar x = \frac{\sum x_{i}}{n}
$$
:::

Er kann wie folgt auch aus der Häufigkeitstabelle berechnet werden:  

$$
\bar x = \frac{\sum x_{i} \cdot h_{i}}{n} = \sum x_{i} \cdot f_{i}
$$

In den meisten Fällen ist der arithmetische Mittelwert derjenige Wert, der die beobachteten Werte in der Stichprobe am besten darstellt. 

::: {.callout-important appearance="default"}
## Merke

Das arithmetische Mittel kann nur bei metrischen Daten berechnet werden!
:::


Für das Beispiel der Erhebung von Kindern in Familien lautet das arithmetische Mittel:

$$
\begin{align*}
\bar{x} &= \frac{1+2+4+2+2+2+3+2+1+1+0+2+2}{25}+\\
&+\frac{0+2+2+1+2+2+3+1+2+2+1+2}{25} = \frac{44}{25} = 1.76 \mbox{ Kinder}.
\end{align*}
$$

Die Berechnung von $\bar x$ über die Häufigkeitstabelle

| $x_{i}$ | $h_{i}$ | $f_{i}$   | $x_{i} \cdot h_{i}$ | $x_{i} \cdot f_{i}$ |
|----|----|------|--------|--------|
| 0  | 2  | 0.08 | 0      | 0      |
| 1  | 6  | 0.24 | 6      | 0.24   |
| 2  | 14 | 0.56 | 28     | 1.12   |
| 3  | 2  | 0.08 | 6      | 0.24   |
| 4  | 1  | 0.04 | 4      | 0.16   |
| $\sum$  | 25 | 1    | 44     | 1.76   |

erfolgt mit:

$$
\bar{x} = \frac{\sum x_{i} \cdot n_i}{n} = \frac{44}{25}= 1.76\mbox{ Kinder} \qquad \bar{x}=\sum{x_{i} \cdot f_i} = 1.76 \mbox{
Kinder}.
$$
Dies ist die Anzahl an Kinder, durch welche die Familien in der Stichprobe am besten repräsentiert werden.


Verwenden wir die Daten der Körpergröße von Studierenden, berechnet sich $\bar x$ wie folgt:


$$
\bar{x} = \frac{179+173+\cdots+187}{30} = 175.07 \mbox{ cm}.
$$

Über die klassierte Häufigkeitstabelle kann $\bar x$ bestimmt werden, indem jeweils die Klassenmitte als $x_i$ verwendet wird.

| X         | $x_i$  | $h_i$ | $f_i$   | $x_i \cdot h_i$ | $x_i \cdot f_i$  |
|-----------|-----|----|------|--------|---------|
| (150,160] | 155 | 2  | 0.07 | 310    | 10.33   |
| (160,170] | 165 | 8  | 0.27 | 1320   | 44.00   |
| (170,180] | 175 | 11 | 0.36 | 1925   | 64.17   |
| (180,190] | 185 | 7  | 0.23 | 1295   | 43.17   |
| (190,200] | 195 | 2  | 0.07 | 390    | 13.00   |
| ∑         |     | 30 | 1    | 5240   | 174.67  |



$$
\bar{x} = \frac{\sum x_i \cdot h_i}{n} = \frac{5240}{30}= 174.67 \mbox{ cm}\qquad \bar{x}=\sum{x_i \cdot f_i} = 174.67 \mbox{ cm}.
$$

Beachten Sie, dass der Mittelwert, der aus der Tabelle berechnet wird, etwas von dem realen Wert abweicht. Da in den Berechnungen jeweils die **Klassenmitten** anstelle der tatsächlichen Werte verwendet werden, ergeben sich dadurch leichte Rundungsfehler.







### Gewichtetes Mittel  

In einigen Fällen haben die Werte der Stichprobe unterschiedliche Bedeutung. In diesem Fall muss die Bedeutung oder der Gewicht 
von jedem Wert der Stichprobe berücksichtigt werden, wenn das Mittel berechnet wird.  

**Definition 10 (Gewichtetes Mittel \(\overline{x}_w\))**. Gegeben eine Stichprobe von Werten $x_1, \ldots, x_n$, wobei jeder  Wert $x_i$ einen Gewicht $w_i$ hat, ist das gewichtete Mittel der Variablen $X$ gegeben durch die Summe der Produkte jedes 
Wertes mit seinem Gewicht, dividiert durch die Summe der Gewichte:  
$$
\overline{x}_w = \frac{\sum x_i w_i}{\sum w_i}

$$
Aus der Häufigkeitstabelle kann mit der Formel berechnet werden:  

$$
\overline{x}_w = \frac{\sum x_i w_i n_i}{\sum w_i}
$$


Ein Student möchte einen repräsentativen Maßstab für sein/zwei Leistung in einem Kurs berechnen. Die Note und die Kreditpunkte 
jeder Fächer sind wie folgt:

| Modul   | Credits | Note |
|-----------|---------|-------|
| Mathe     | 6       | 2     |
| Wirtschaft | 4       | 3     |
| Chemie   | 8       | 1     |



Fächertabelle
Kreditpunkte
Note
Mathematik
6
5
Wirtschaft
4
3
Chemie
8
6

Die arithmetische Mitte beträgt ∑𝑥𝑖 /𝑛 = (5+3+6)/3 = 4,67 Punkte,

Allerdings gibt diese Maßzahl nicht gut den Leistungsumstand des Studenten wieder, da nicht alle Fächer die gleiche Bedeutung 
haben und dasselbe Bemühen erfordern, um bestanden zu werden. Fächer mit mehr Kreditpunkten erfordern mehr Arbeit und müssen im 
Berechnung des Durchschnitts ein größeres Gewicht erhalten. In diesem Fall ist es ratsam, den gewichteten Durchschnitt mit den 
Kreditpunkzen als Gewichten zu verwenden.
